/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcervoRouteImport } from './routes/acervo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EdicaoIdRouteImport } from './routes/edicao.$id'

const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcervoRoute = AcervoRouteImport.update({
  id: '/acervo',
  path: '/acervo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EdicaoIdRoute = EdicaoIdRouteImport.update({
  id: '/edicao/$id',
  path: '/edicao/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRoute
  '/admin': typeof AdminRoute
  '/editor': typeof EditorRoute
  '/edicao/$id': typeof EdicaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRoute
  '/admin': typeof AdminRoute
  '/editor': typeof EditorRoute
  '/edicao/$id': typeof EdicaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRoute
  '/admin': typeof AdminRoute
  '/editor': typeof EditorRoute
  '/edicao/$id': typeof EdicaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/acervo' | '/admin' | '/editor' | '/edicao/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/acervo' | '/admin' | '/editor' | '/edicao/$id'
  id: '__root__' | '/' | '/acervo' | '/admin' | '/editor' | '/edicao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcervoRoute: typeof AcervoRoute
  AdminRoute: typeof AdminRoute
  EditorRoute: typeof EditorRoute
  EdicaoIdRoute: typeof EdicaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acervo': {
      id: '/acervo'
      path: '/acervo'
      fullPath: '/acervo'
      preLoaderRoute: typeof AcervoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edicao/$id': {
      id: '/edicao/$id'
      path: '/edicao/$id'
      fullPath: '/edicao/$id'
      preLoaderRoute: typeof EdicaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcervoRoute: AcervoRoute,
  AdminRoute: AdminRoute,
  EditorRoute: EditorRoute,
  EdicaoIdRoute: EdicaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
